// ======================================
// Dentistry-Specific Data Seeds
// ======================================

// Dental Observation Codes based on your dental chart forms
export const dentalObservationCodesSeed = [
  // Conditions
  {
    code: "D",
    category: "condition",
    description: "Decayed (Caries Indicated for Filling)",
    fhirCode: "D001",
  },
  { code: "M", category: "condition", description: "Missing due to Caries", fhirCode: "D002" },
  {
    code: "MO",
    category: "condition",
    description: "Missing due to Other Causes",
    fhirCode: "D003",
  },
  { code: "Im", category: "condition", description: "Impacted Tooth", fhirCode: "D004" },
  { code: "Sp", category: "condition", description: "Supernumerary Tooth", fhirCode: "D005" },
  { code: "Rf", category: "condition", description: "Root Fragment", fhirCode: "D006" },
  { code: "Un", category: "condition", description: "Unerupted", fhirCode: "D007" },

  // Restorations & Prosthetics
  { code: "Am", category: "restoration", description: "Amalgam Filling", fhirCode: "D101" },
  { code: "Co", category: "restoration", description: "Composite Filling", fhirCode: "D102" },
  { code: "JC", category: "restoration", description: "Jacket Crown", fhirCode: "D103" },
  { code: "Ab", category: "restoration", description: "Abutment", fhirCode: "D104" },
  { code: "Att", category: "restoration", description: "Attachment", fhirCode: "D105" },
  { code: "P", category: "restoration", description: "Pontic", fhirCode: "D106" },
  { code: "In", category: "restoration", description: "Inlay", fhirCode: "D107" },
  { code: "Imp", category: "restoration", description: "Implant", fhirCode: "D108" },
  { code: "S", category: "restoration", description: "Sealants", fhirCode: "D109" },
  { code: "Rm", category: "restoration", description: "Removable Denture", fhirCode: "D110" },

  // Surgery
  { code: "X", category: "surgery", description: "Extraction due to Caries", fhirCode: "D201" },
  {
    code: "XO",
    category: "surgery",
    description: "Extraction due to Other Causes",
    fhirCode: "D202",
  },
];

// Tooth Numbering System (FDI Notation)
export const toothNumberingSystemSeed = [
  // Permanent Teeth - Upper Right (1x)
  {
    toothNumber: "18",
    toothName: "Upper Right Third Molar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "17",
    toothName: "Upper Right Second Molar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "16",
    toothName: "Upper Right First Molar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "15",
    toothName: "Upper Right Second Premolar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "14",
    toothName: "Upper Right First Premolar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "13",
    toothName: "Upper Right Canine",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "canine",
    isPermanent: true,
  },
  {
    toothNumber: "12",
    toothName: "Upper Right Lateral Incisor",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "incisor",
    isPermanent: true,
  },
  {
    toothNumber: "11",
    toothName: "Upper Right Central Incisor",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "incisor",
    isPermanent: true,
  },

  // Permanent Teeth - Upper Left (2x)
  {
    toothNumber: "21",
    toothName: "Upper Left Central Incisor",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "incisor",
    isPermanent: true,
  },
  {
    toothNumber: "22",
    toothName: "Upper Left Lateral Incisor",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "incisor",
    isPermanent: true,
  },
  {
    toothNumber: "23",
    toothName: "Upper Left Canine",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "canine",
    isPermanent: true,
  },
  {
    toothNumber: "24",
    toothName: "Upper Left First Premolar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "25",
    toothName: "Upper Left Second Premolar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "26",
    toothName: "Upper Left First Molar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "27",
    toothName: "Upper Left Second Molar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "28",
    toothName: "Upper Left Third Molar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "molar",
    isPermanent: true,
  },

  // Permanent Teeth - Lower Left (3x)
  {
    toothNumber: "38",
    toothName: "Lower Left Third Molar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "37",
    toothName: "Lower Left Second Molar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "36",
    toothName: "Lower Left First Molar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "35",
    toothName: "Lower Left Second Premolar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "34",
    toothName: "Lower Left First Premolar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "33",
    toothName: "Lower Left Canine",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "canine",
    isPermanent: true,
  },
  {
    toothNumber: "32",
    toothName: "Lower Left Lateral Incisor",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "incisor",
    isPermanent: true,
  },
  {
    toothNumber: "31",
    toothName: "Lower Left Central Incisor",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "incisor",
    isPermanent: true,
  },

  // Permanent Teeth - Lower Right (4x)
  {
    toothNumber: "41",
    toothName: "Lower Right Central Incisor",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "incisor",
    isPermanent: true,
  },
  {
    toothNumber: "42",
    toothName: "Lower Right Lateral Incisor",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "incisor",
    isPermanent: true,
  },
  {
    toothNumber: "43",
    toothName: "Lower Right Canine",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "canine",
    isPermanent: true,
  },
  {
    toothNumber: "44",
    toothName: "Lower Right First Premolar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "45",
    toothName: "Lower Right Second Premolar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "premolar",
    isPermanent: true,
  },
  {
    toothNumber: "46",
    toothName: "Lower Right First Molar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "47",
    toothName: "Lower Right Second Molar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "molar",
    isPermanent: true,
  },
  {
    toothNumber: "48",
    toothName: "Lower Right Third Molar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "molar",
    isPermanent: true,
  },

  // Deciduous Teeth - Upper Right (5x)
  {
    toothNumber: "55",
    toothName: "Upper Right Second Molar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "molar",
    isPermanent: false,
  },
  {
    toothNumber: "54",
    toothName: "Upper Right First Molar",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "molar",
    isPermanent: false,
  },
  {
    toothNumber: "53",
    toothName: "Upper Right Canine",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "canine",
    isPermanent: false,
  },
  {
    toothNumber: "52",
    toothName: "Upper Right Lateral Incisor",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "incisor",
    isPermanent: false,
  },
  {
    toothNumber: "51",
    toothName: "Upper Right Central Incisor",
    arch: "upper",
    quadrant: "upper_right",
    toothType: "incisor",
    isPermanent: false,
  },

  // Deciduous Teeth - Upper Left (6x)
  {
    toothNumber: "61",
    toothName: "Upper Left Central Incisor",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "incisor",
    isPermanent: false,
  },
  {
    toothNumber: "62",
    toothName: "Upper Left Lateral Incisor",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "incisor",
    isPermanent: false,
  },
  {
    toothNumber: "63",
    toothName: "Upper Left Canine",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "canine",
    isPermanent: false,
  },
  {
    toothNumber: "64",
    toothName: "Upper Left First Molar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "molar",
    isPermanent: false,
  },
  {
    toothNumber: "65",
    toothName: "Upper Left Second Molar",
    arch: "upper",
    quadrant: "upper_left",
    toothType: "molar",
    isPermanent: false,
  },

  // Deciduous Teeth - Lower Left (7x)
  {
    toothNumber: "75",
    toothName: "Lower Left Second Molar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "molar",
    isPermanent: false,
  },
  {
    toothNumber: "74",
    toothName: "Lower Left First Molar",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "molar",
    isPermanent: false,
  },
  {
    toothNumber: "73",
    toothName: "Lower Left Canine",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "canine",
    isPermanent: false,
  },
  {
    toothNumber: "72",
    toothName: "Lower Left Lateral Incisor",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "incisor",
    isPermanent: false,
  },
  {
    toothNumber: "71",
    toothName: "Lower Left Central Incisor",
    arch: "lower",
    quadrant: "lower_left",
    toothType: "incisor",
    isPermanent: false,
  },

  // Deciduous Teeth - Lower Right (8x)
  {
    toothNumber: "81",
    toothName: "Lower Right Central Incisor",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "incisor",
    isPermanent: false,
  },
  {
    toothNumber: "82",
    toothName: "Lower Right Lateral Incisor",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "incisor",
    isPermanent: false,
  },
  {
    toothNumber: "83",
    toothName: "Lower Right Canine",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "canine",
    isPermanent: false,
  },
  {
    toothNumber: "84",
    toothName: "Lower Right First Molar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "molar",
    isPermanent: false,
  },
  {
    toothNumber: "85",
    toothName: "Lower Right Second Molar",
    arch: "lower",
    quadrant: "lower_right",
    toothType: "molar",
    isPermanent: false,
  },
];

// Dental Procedure Codes (ADA Codes)
export const dentalProcedureCodesSeed = [
  // Preventive Services
  {
    code: "D0150",
    category: "preventive",
    description: "Comprehensive oral evaluation",
    fhirCode: "D0150",
    typicalDuration: 60,
  },
  {
    code: "D0160",
    category: "preventive",
    description: "Detailed and extensive oral evaluation",
    fhirCode: "D0160",
    typicalDuration: 90,
  },
  {
    code: "D1110",
    category: "preventive",
    description: "Prophylaxis - adult",
    fhirCode: "D1110",
    typicalDuration: 60,
  },
  {
    code: "D1120",
    category: "preventive",
    description: "Prophylaxis - child",
    fhirCode: "D1120",
    typicalDuration: 30,
  },
  {
    code: "D1206",
    category: "preventive",
    description: "Topical application of fluoride varnish",
    fhirCode: "D1206",
    typicalDuration: 15,
  },

  // Restorative Services
  {
    code: "D2140",
    category: "restorative",
    description: "Amalgam - one surface, primary or permanent",
    fhirCode: "D2140",
    typicalDuration: 45,
  },
  {
    code: "D2150",
    category: "restorative",
    description: "Amalgam - two surfaces, primary or permanent",
    fhirCode: "D2150",
    typicalDuration: 60,
  },
  {
    code: "D2391",
    category: "restorative",
    description: "Resin-based composite - one surface, anterior",
    fhirCode: "D2391",
    typicalDuration: 45,
  },
  {
    code: "D2392",
    category: "restorative",
    description: "Resin-based composite - two surfaces, anterior",
    fhirCode: "D2392",
    typicalDuration: 60,
  },

  // Endodontic Services
  {
    code: "D3310",
    category: "endodontic",
    description: "Endodontic therapy, anterior tooth",
    fhirCode: "D3310",
    typicalDuration: 120,
  },
  {
    code: "D3320",
    category: "endodontic",
    description: "Endodontic therapy, bicuspid tooth",
    fhirCode: "D3320",
    typicalDuration: 150,
  },
  {
    code: "D3330",
    category: "endodontic",
    description: "Endodontic therapy, molar",
    fhirCode: "D3330",
    typicalDuration: 180,
  },

  // Periodontic Services
  {
    code: "D4341",
    category: "periodontic",
    description: "Periodontal scaling and root planing - one to three teeth",
    fhirCode: "D4341",
    typicalDuration: 60,
  },
  {
    code: "D4342",
    category: "periodontic",
    description: "Periodontal scaling and root planing - four or more teeth",
    fhirCode: "D4342",
    typicalDuration: 90,
  },

  // Oral and Maxillofacial Surgery
  {
    code: "D7140",
    category: "surgical",
    description: "Extraction, erupted tooth",
    fhirCode: "D7140",
    typicalDuration: 30,
  },
  {
    code: "D7210",
    category: "surgical",
    description: "Extraction, erupted tooth requiring removal of bone",
    fhirCode: "D7210",
    typicalDuration: 60,
  },
  {
    code: "D7240",
    category: "surgical",
    description: "Removal of impacted tooth - soft tissue",
    fhirCode: "D7240",
    typicalDuration: 90,
  },
  {
    code: "D7241",
    category: "surgical",
    description: "Removal of impacted tooth - partially bony",
    fhirCode: "D7241",
    typicalDuration: 120,
  },

  // Prosthodontics
  {
    code: "D2740",
    category: "prosthodontic",
    description: "Crown - porcelain/ceramic substrate",
    fhirCode: "D2740",
    typicalDuration: 120,
  },
  {
    code: "D6240",
    category: "prosthodontic",
    description: "Pontic - porcelain/ceramic",
    fhirCode: "D6240",
    typicalDuration: 90,
  },
  {
    code: "D5110",
    category: "prosthodontic",
    description: "Complete denture - maxillary",
    fhirCode: "D5110",
    typicalDuration: 300,
  },
  {
    code: "D5120",
    category: "prosthodontic",
    description: "Complete denture - mandibular",
    fhirCode: "D5120",
    typicalDuration: 300,
  },
];
